### ISSUE TITLE
Script that checks if the ~README~ storybook file exists in the component

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique-galaxy#13]
The script should check if every components have their README file. If not, the script fails.

**Comment by punix81** [comment]
@ice-blaze  Do we still need this task if we use the storybook?

**Comment by ice-blaze** [comment]
Maybe we can update it. Instead of checking if there is a README file check that the component is in the story book. Do you think it would make sens?

**Comment by ice-blaze** [comment]
We are closing this issue because there was already an issue to use stoybook instead of readmefile
